language: ruby
rvm:
 - 2.4.2

bundler_args: --without "development"

before_install: gem install bundler

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

services:
  - postgresql

addons:
  postgresql: "9.6"

env:
  global:
    - CC_TEST_REPORTER_ID=c73dfb9fe52e66e1852c212c35bd8b4ad3a19b4ca5db915340c457a833bab143